// Manual aliases: conjugated/irregular forms -> infinitive lemma
// These are checked by findStrongFallback before the generic lemmatizer.
// The infinitive must exist as a key in STRONG_INDEX.single for the lookup to work.

const MANUAL_ALIASES = {

    // --- DECIR (to say) ---
    "dijo": "decir",
    "dijeron": "decir",
    "dijiste": "decir",
    "dijimos": "decir",
    "dijese": "decir",
    "dijeren": "decir",
    "dijera": "decir",
    "dijeras": "decir",
    "dijeran": "decir",
    "dijesen": "decir",
    "diciendo": "decir",
    "dice": "decir",
    "dicen": "decir",
    "dices": "decir",
    "digamos": "decir",
    "digan": "decir",
    "digas": "decir",
    "diga": "decir",
    "digáis": "decir",
    "dirá": "decir",
    "dirán": "decir",
    "diré": "decir",
    "dirás": "decir",
    "diría": "decir",
    "dirían": "decir",
    "dicho": "decir",
    "di": "decir",
    "decid": "decir",
    "dí": "decir",

    // --- HACER (to do/make) ---
    "hizo": "hacer",
    "hicieron": "hacer",
    "hice": "hacer",
    "hiciste": "hacer",
    "hicimos": "hacer",
    "hiciera": "hacer",
    "hicieran": "hacer",
    "hicieras": "hacer",
    "hiciese": "hacer",
    "hiciesen": "hacer",
    "hiciere": "hacer",
    "hicieren": "hacer",
    "haciendo": "hacer",
    "hace": "hacer",
    "hacen": "hacer",
    "haces": "hacer",
    "hago": "hacer",
    "hagas": "hacer",
    "haga": "hacer",
    "hagamos": "hacer",
    "hagáis": "hacer",
    "hagan": "hacer",
    "haré": "hacer",
    "harás": "hacer",
    "hará": "hacer",
    "haremos": "hacer",
    "haréis": "hacer",
    "harán": "hacer",
    "haría": "hacer",
    "harías": "hacer",
    "harían": "hacer",
    "haz": "hacer",
    "haced": "hacer",
    "hecho": "hacer",

    // --- DAR (to give) ---
    "dio": "dar",
    "dieron": "dar",
    "diste": "dar",
    "dimos": "dar",
    "di": "dar",
    "da": "dar",
    "dan": "dar",
    "daba": "dar",
    "daban": "dar",
    "dado": "dar",
    "daré": "dar",
    "darás": "dar",
    "dará": "dar",
    "daremos": "dar",
    "daréis": "dar",
    "darán": "dar",
    "daría": "dar",
    "darían": "dar",
    "dase": "dar",
    "deme": "dar",
    "dad": "dar",

    // --- PONER (to put) ---
    "puso": "poner",
    "pusieron": "poner",
    "puse": "poner",
    "pusiste": "poner",
    "pusimos": "poner",
    "pusiera": "poner",
    "pusieran": "poner",
    "pusiese": "poner",
    "pusiesen": "poner",
    "pusiere": "poner",
    "pusieren": "poner",
    "poniendo": "poner",
    "pone": "poner",
    "ponen": "poner",
    "pones": "poner",
    "pongo": "poner",
    "pongas": "poner",
    "ponga": "poner",
    "pongamos": "poner",
    "pongáis": "poner",
    "pongan": "poner",
    "pondré": "poner",
    "pondrás": "poner",
    "pondrá": "poner",
    "pondremos": "poner",
    "pondréis": "poner",
    "pondrán": "poner",
    "pondría": "poner",
    "pondrían": "poner",
    "pon": "poner",
    "poned": "poner",
    "puesto": "poner",

    // --- TENER (to have) ---
    "tuvo": "tener",
    "tuvieron": "tener",
    "tuve": "tener",
    "tuviste": "tener",
    "tuvimos": "tener",
    "tuviera": "tener",
    "tuvieran": "tener",
    "tuviese": "tener",
    "tuviesen": "tener",
    "tuviere": "tener",
    "tuvieren": "tener",
    "teniendo": "tener",
    "tiene": "tener",
    "tienen": "tener",
    "tienes": "tener",
    "tengo": "tener",
    "tengas": "tener",
    "tenga": "tener",
    "tengamos": "tener",
    "tengáis": "tener",
    "tengan": "tener",
    "tendré": "tener",
    "tendrás": "tener",
    "tendrá": "tener",
    "tendremos": "tener",
    "tendréis": "tener",
    "tendrán": "tener",
    "tendría": "tener",
    "tendrías": "tener",
    "tendrían": "tener",
    "ten": "tener",
    "tened": "tener",

    // --- VENIR (to come) ---
    "vino": "venir",
    "vinieron": "venir",
    "vine": "venir",
    "viniste": "venir",
    "vinimos": "venir",
    "viniera": "venir",
    "vinieran": "venir",
    "viniese": "venir",
    "viniesen": "venir",
    "viniere": "venir",
    "vinieren": "venir",
    "viniendo": "venir",
    "viene": "venir",
    "vienen": "venir",
    "vienes": "venir",
    "vengo": "venir",
    "vengas": "venir",
    "venga": "venir",
    "vengamos": "venir",
    "vengáis": "venir",
    "vengan": "venir",
    "vendré": "venir",
    "vendrás": "venir",
    "vendrá": "venir",
    "vendremos": "venir",
    "vendréis": "venir",
    "vendrán": "venir",
    "vendría": "venir",
    "vendríais": "venir",
    "vendrían": "venir",
    "ven": "venir",
    "venid": "venir",

    // --- VER (to see) ---
    "vio": "ver",
    "vieron": "ver",
    "vi": "ver",
    "viste": "ver",
    "vimos": "ver",
    "viera": "ver",
    "vieran": "ver",
    "viese": "ver",
    "viesen": "ver",
    "viere": "ver",
    "vieren": "ver",
    "viendo": "ver",
    "ve": "ver",
    "ves": "ver",
    "ven": "ver",
    "veo": "ver",
    "veas": "ver",
    "vea": "ver",
    "veamos": "ver",
    "veáis": "ver",
    "vean": "ver",
    "veré": "ver",
    "verás": "ver",
    "verá": "ver",
    "veremos": "ver",
    "verán": "ver",
    "vería": "ver",
    "verías": "ver",
    "verían": "ver",
    "visto": "ver",
    "ve": "ver",
    "ved": "ver",

    // --- SER (to be) ---
    "era": "ser",
    "eras": "ser",
    "éramos": "ser",
    "eran": "ser",
    "fui": "ser",
    "fuiste": "ser",
    "fue": "ser",
    "fuimos": "ser",
    "fuisteis": "ser",
    "fueron": "ser",
    "fuera": "ser",
    "fueras": "ser",
    "fuéramos": "ser",
    "fueran": "ser",
    "fuese": "ser",
    "fueses": "ser",
    "fuésemos": "ser",
    "fuesen": "ser",
    "fuere": "ser",
    "fueres": "ser",
    "fuéremos": "ser",
    "fueren": "ser",
    "seré": "ser",
    "serás": "ser",
    "será": "ser",
    "seremos": "ser",
    "seréis": "ser",
    "serán": "ser",
    "sería": "ser",
    "serías": "ser",
    "seríamos": "ser",
    "serían": "ser",
    "sé": "ser",
    "sed": "ser",
    "sido": "ser",
    "siendo": "ser",

    // --- ESTAR (to be) ---
    "estuve": "estar",
    "estuviste": "estar",
    "estuvo": "estar",
    "estuvimos": "estar",
    "estuvisteis": "estar",
    "estuvieron": "estar",
    "estuviera": "estar",
    "estuvieras": "estar",
    "estuviéramos": "estar",
    "estuvieran": "estar",
    "estuviese": "estar",
    "estuvieses": "estar",
    "estuviésemos": "estar",
    "estuviesen": "estar",
    "estuviere": "estar",
    "estuvieres": "estar",
    "estuviéremos": "estar",
    "estuvieren": "estar",
    "estando": "estar",
    "estado": "estar",
    "esté": "estar",
    "estés": "estar",
    "estén": "estar",
    "estemos": "estar",
    "estéis": "estar",

    // --- HABER (to have auxiliary) ---
    "hubo": "haber",
    "hubieron": "haber",
    "hube": "haber",
    "hubiste": "haber",
    "hubimos": "haber",
    "hubiera": "haber",
    "hubieras": "haber",
    "hubiéramos": "haber",
    "hubieran": "haber",
    "hubiese": "haber",
    "hubieses": "haber",
    "hubiésemos": "haber",
    "hubiesen": "haber",
    "hubiere": "haber",
    "hubieres": "haber",
    "hubiéremos": "haber",
    "hubieren": "haber",
    "habido": "haber",
    "habré": "haber",
    "habrás": "haber",
    "habrá": "haber",
    "habremos": "haber",
    "habréis": "haber",
    "habrán": "haber",
    "habría": "haber",
    "habrías": "haber",
    "habríamos": "haber",
    "habrían": "haber",
    "haya": "haber",
    "hayas": "haber",
    "hayamos": "haber",
    "hayáis": "haber",
    "hayan": "haber",

    // --- PODER (to be able) ---
    "pudo": "poder",
    "pudieron": "poder",
    "pude": "poder",
    "pudiste": "poder",
    "pudimos": "poder",
    "pudiera": "poder",
    "pudieran": "poder",
    "pudiese": "poder",
    "pudiesen": "poder",
    "pudiere": "poder",
    "pudieren": "poder",
    "pudiendo": "poder",
    "puedo": "poder",
    "puedes": "poder",
    "puede": "poder",
    "podemos": "poder",
    "podéis": "poder",
    "pueden": "poder",
    "pueda": "poder",
    "puedas": "poder",
    "podamos": "poder",
    "podáis": "poder",
    "puedan": "poder",
    "podré": "poder",
    "podrás": "poder",
    "podrá": "poder",
    "podremos": "poder",
    "podréis": "poder",
    "podrán": "poder",
    "podría": "poder",
    "podrías": "poder",
    "podríamos": "poder",
    "podrían": "poder",
    "pudiendo": "poder",

    // --- SABER (to know) ---
    "supo": "saber",
    "supieron": "saber",
    "supe": "saber",
    "supiste": "saber",
    "supimos": "saber",
    "supiera": "saber",
    "supieran": "saber",
    "supiese": "saber",
    "supiesen": "saber",
    "supiere": "saber",
    "supieren": "saber",
    "sabiendo": "saber",
    "sé": "saber",
    "sabes": "saber",
    "sabe": "saber",
    "sabemos": "saber",
    "sabéis": "saber",
    "saben": "saber",
    "sepa": "saber",
    "sepas": "saber",
    "sepamos": "saber",
    "sepáis": "saber",
    "sepan": "saber",
    "sabré": "saber",
    "sabrás": "saber",
    "sabrá": "saber",
    "sabremos": "saber",
    "sabréis": "saber",
    "sabrán": "saber",
    "sabría": "saber",
    "sabríais": "saber",
    "sabrían": "saber",

    // --- QUERER (to want) ---
    "quiso": "querer",
    "quisieron": "querer",
    "quise": "querer",
    "quisiste": "querer",
    "quisimos": "querer",
    "quisiera": "querer",
    "quisieran": "querer",
    "quisiese": "querer",
    "quisiesen": "querer",
    "quisiere": "querer",
    "quisieren": "querer",
    "queriendo": "querer",
    "quiero": "querer",
    "quieres": "querer",
    "quiere": "querer",
    "queremos": "querer",
    "queréis": "querer",
    "quieren": "querer",
    "quiera": "querer",
    "quieras": "querer",
    "queramos": "querer",
    "queráis": "querer",
    "quieran": "querer",
    "querré": "querer",
    "querrás": "querer",
    "querrá": "querer",
    "querremos": "querer",
    "querréis": "querer",
    "querrán": "querer",
    "querría": "querer",
    "querrías": "querer",
    "querrían": "querer",

    // --- TRAER (to bring) ---
    "trajo": "traer",
    "trajeron": "traer",
    "traje": "traer",
    "trajiste": "traer",
    "trajimos": "traer",
    "trajera": "traer",
    "trajeran": "traer",
    "trajese": "traer",
    "trajesen": "traer",
    "trajere": "traer",
    "trajeren": "traer",
    "trayendo": "traer",
    "traigo": "traer",
    "traes": "traer",
    "trae": "traer",
    "traemos": "traer",
    "traéis": "traer",
    "traen": "traer",
    "traiga": "traer",
    "traigas": "traer",
    "traigamos": "traer",
    "traigáis": "traer",
    "traigan": "traer",

    // --- ANDAR (to walk) ---
    "anduvo": "andar",
    "anduvieron": "andar",
    "anduve": "andar",
    "anduviste": "andar",
    "anduvimos": "andar",
    "anduviera": "andar",
    "anduvieran": "andar",
    "anduviese": "andar",
    "anduviesen": "andar",

    // --- CONDUCIR / PRODUCIR / INTRODUCIR pattern ---
    "condujo": "conducir",
    "condujeron": "conducir",
    "produjo": "producir",
    "produjeron": "producir",
    "introdujo": "introducir",
    "introdujeron": "introducir",
    "redujo": "reducir",
    "redujeron": "reducir",
    "tradujo": "traducir",
    "tradujeron": "traducir",

    // --- SALIR (to go out) ---
    "salió": "salir",
    "salieron": "salir",
    "salí": "salir",
    "saliste": "salir",
    "salimos": "salir",
    "saldré": "salir",
    "saldrás": "salir",
    "saldrá": "salir",
    "saldremos": "salir",
    "saldréis": "salir",
    "saldrán": "salir",
    "salgo": "salir",
    "sales": "salir",
    "sale": "salir",
    "salimos": "salir",
    "salís": "salir",
    "salen": "salir",
    "salga": "salir",
    "salgas": "salir",
    "salgamos": "salir",
    "salgáis": "salir",
    "salgan": "salir",
    "sal": "salir",
    "salid": "salir",

    // --- VOLVER (to return) ---
    "volvió": "volver",
    "volvieron": "volver",
    "volví": "volver",
    "volviste": "volver",
    "volvimos": "volver",
    "volviera": "volver",
    "volvieran": "volver",
    "volviese": "volver",
    "volviesen": "volver",
    "volviere": "volver",
    "volvieren": "volver",
    "volviendo": "volver",
    "vuelvo": "volver",
    "vuelves": "volver",
    "vuelve": "volver",
    "volvemos": "volver",
    "volvéis": "volver",
    "vuelven": "volver",
    "vuelva": "volver",
    "vuelvas": "volver",
    "volvamos": "volver",
    "volváis": "volver",
    "vuelvan": "volver",

    // --- RESPONDER (to answer) ---
    "respondió": "responder",
    "respondieron": "responder",
    "respondí": "responder",
    "respondiste": "responder",
    "respondimos": "responder",
    "respondiera": "responder",
    "respondieran": "responder",
    "respondiese": "responder",
    "respondiesen": "responder",
    "respondiendo": "responder",
    "respondo": "responder",
    "respondes": "responder",
    "responde": "responder",
    "respondemos": "responder",
    "respondéis": "responder",
    "responden": "responder",

    // --- CUBRIR (to cover) ---
    "cubrió": "cubrir",
    "cubrieron": "cubrir",
    "cubrí": "cubrir",
    "cubriste": "cubrir",
    "cubrimos": "cubrir",
    "cubriera": "cubrir",
    "cubrieran": "cubrir",
    "cubriese": "cubrir",
    "cubriesen": "cubrir",
    "cubriendo": "cubrir",
    "cubro": "cubrir",
    "cubres": "cubrir",
    "cubre": "cubrir",
    "cubrimos": "cubrir",
    "cubrís": "cubrir",
    "cubren": "cubrir",
    "cubierto": "cubrir",

    // --- ABRIR (to open) ---
    "abrió": "abrir",
    "abrieron": "abrir",
    "abierto": "abrir",

    // --- REUNIR (to gather) ---
    "reunió": "reunir",
    "reunieron": "reunir",

    // --- MORIR (to die) ---
    "murió": "morir",
    "murieron": "morir",
    "muerto": "morir",

    // --- DORMIR (to sleep) ---
    "durmió": "dormir",
    "durmieron": "dormir",

    // --- SERVIR (to serve) ---
    "sirvió": "servir",
    "sirvieron": "servir",

    // --- PEDIR (to ask for) ---
    "pidió": "pedir",
    "pidieron": "pedir",

    // --- OÍR (to hear) ---
    "oyó": "oír",
    "oyeron": "oír",
    "oído": "oír",
    "oyendo": "oír",
    "oigo": "oír",
    "oyes": "oír",
    "oye": "oír",
    "oímos": "oír",
    "oís": "oír",
    "oyen": "oír",
    "oiga": "oír",
    "oigas": "oír",
    "oigan": "oír",

    // --- LEVANTAR (with enclitic pronouns) ---
    "levantate": "levantar",
    "levantad": "levantar",

    // --- ENTRAR (enter) ---
    "entró": "entrar",
    "entraron": "entrar",
    "entré": "entrar",
    "entraste": "entrar",
    "entramos": "entrar",
    "entra": "entrar",
    "entran": "entrar",
    "entraba": "entrar",
    "entraban": "entrar",

    // --- PASAR ---
    "pasó": "pasar",
    "pasaron": "pasar",

    // --- LLEGAR ---
    "llegó": "llegar",
    "llegaron": "llegar",

    // --- SACAR ---
    "sacó": "sacar",
    "sacaron": "sacar",

    // --- BUSCAR ---
    "buscó": "buscar",
    "buscaron": "buscar",

    // --- TOCAR ---
    "tocó": "tocar",
    "tocaron": "tocar",

    // --- PECAR ---
    "pecó": "pecar",
    "pecaron": "pecar",

    // --- EXPLICAR ---
    "explicó": "explicar",
    "explicaron": "explicar",

    // --- COMUNICAR ---
    "comunicó": "comunicar",
    "comunicaron": "comunicar",

    // --- DEDICAR ---
    "dedicó": "dedicar",
    "dedicaron": "dedicar",

    // --- COLOCAR ---
    "colocó": "colocar",
    "colocaron": "colocar",

    // --- INDICAR ---
    "indicó": "indicar",
    "indicaron": "indicar",

    // --- PLURAL/SINGULAR NOUN ALIASES ---  
    "hijos": "hijo",
    "reyes": "rey",
    "mujeres": "mujer",
    "varones": "varón",
    "hijas": "hija",
    "siervos": "siervo",
    "siervas": "sierva",
    "sacerdotes": "sacerdote",
    "levitas": "levita",
    "profetas": "profeta",
    "apóstoles": "apóstol",
    "discípulos": "discípulo",
    "fariseos": "fariseo",
    "escribas": "escriba",
    "gentiles": "gentil",
    "judíos": "judío",
    "hermanos": "hermano",
    "hermanas": "hermana",
    "padres": "padre",
    "madres": "madre",
    "hombres": "hombre",
    "palabras": "palabra",
    "mandamientos": "mandamiento",
    "pecados": "pecado",
    "ciudades": "ciudad",
    "naciones": "nación",
    "tribus": "tribu",
    "ejércitos": "ejército",
    "altares": "altar",
    "animales": "animal",
    "camellos": "camello",
    "caballos": "caballo",
    "carros": "carro",
    "casas": "casa",
    "campos": "campo",
    "montes": "monte",
    "ríos": "río",
    "fuentes": "fuente",
    "puertas": "puerta",
    "murallas": "muralla",
    "torres": "torre",
    "calles": "calle",
    "pisos": "piso",
    "dioses": "dios",
    "reyes": "rey",
    "príncipes": "príncipe",
    "jueces": "juez",
    "ancianos": "anciano",
    "jóvenes": "joven",
    "niños": "niño",
    "niñas": "niña",
    "bienes": "bien",
    "males": "mal",
    "días": "día",
    "noches": "noche",
    "años": "año",
    "meses": "mes",
    "tiempos": "tiempo",
    "siglos": "siglo",
    "generaciones": "generación",
    "corazones": "corazón",
    "manos": "mano",
    "pies": "pie",
    "ojos": "ojo",
    "oídos": "oído",
    "labios": "labio",
    "vestidos": "vestido",
    "panes": "pan",
    "peces": "pez",
    "aves": "ave",
    "bestias": "bestia",
    "piedras": "piedra",
    "árboles": "árbol",
    "frutos": "fruto",
    "semillas": "semilla",
    "espinas": "espina",
    "flores": "flor",
    "campos": "campo",
    "valles": "valle",
    "collados": "collado",
    "llanuras": "llanura",
    "desiertos": "desierto",
    "caminos": "camino",
    "sendas": "senda",
    "veredas": "vereda",

    // --- ADJECTIVE PLURALS ---
    "santas": "santo",
    "santos": "santo",
    "justos": "justo",
    "justas": "justa",
    "malos": "malo",
    "malas": "mala",
    "buenos": "bueno",
    "buenas": "buena",
    "grandes": "grande",
    "pequeños": "pequeño",
    "pequeñas": "pequeña",
    "hermosas": "hermosa",
    "hermosos": "hermoso",
    "fieles": "fiel",

    // --- COMMON APOCOPES ---
    "buen": "bueno",
    "gran": "grande",
    "mal": "malo",
    "ningun": "ninguno",
    "primer": "primero",
    "tercer": "tercero",

    // --- POSSESSIVES ---
    "vuestra": "vuestro",
    "vuestras": "vuestro",
    "vuestros": "vuestro",
    "nuestra": "nuestro",
    "nuestras": "nuestro",
    "nuestros": "nuestro",
    "suyo": "suyo",
    "suya": "suyo",
    "suyos": "suyo",
    "suyas": "suyo",
    "mía": "mío",
    "mías": "mío",
    "mío": "mío",
    "míos": "mío",
    "tuya": "tuyo",
    "tuyas": "tuyo",
    "tuyos": "tuyo",
    "tuya": "tuyo",

    // --- DEMONSTRATIVE FEM/PLURALS ---
    "esta": "este",
    "estas": "este",
    "estos": "este",
    "esa": "ese",
    "esas": "ese",
    "esos": "ese",
    "aquella": "aquel",
    "aquellas": "aquel",
    "aquellos": "aquel",

    // --- RELATIVE/INTERROGATIVE ---
    "cuya": "cuyo",
    "cuyas": "cuyo",
    "cuyos": "cuyo",
    "cuales": "cual",
    "quienes": "quien",

    // --- ADVERBS / OTHER ---
    "acerca": "acerca",
    "acaso": "acaso",
    "arriba": "arriba",
    "adonde": "adonde",
    "consigo": "consigo",
    "respecto": "respecto",

    // --- PARTICIPLES used as adjectives ---
    "fortificadas": "fortificado",
    "fortificados": "fortificado",
    "amadas": "amado",
    "amados": "amado",
    "amada": "amado",
    "amado": "amado",
    "escogidos": "escogido",
    "escogidas": "escogido",
    "escogida": "escogido",
    "escogido": "escogido",
    "llamados": "llamado",
    "llamadas": "llamado",
    "llamada": "llamado",
    "llamado": "llamado",
    "escrito": "escribir",
    "escritos": "escribir",
    "escritas": "escribir",
    "muerto": "morir",
    "muertos": "morir",
    "muertas": "morir",
};
